### ISSUE TITLE
Error when visiting /stats (lnvalidArgumentException: Illegal operator)

### ISSUE THREAD

**Issue by michaeljhopkins** [antonioribeiro/tracker#127]
I get the following issue when hitting `/stats`. Any ideas? It's a bit out of my areas of expertise

```
[2015-11-25 18:11:19] production.ERROR: InvalidArgumentException: Illegal operator and value combination. in /home/forge/michaeljhopkins.com/releases/20151125180207/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:466
Stack trace:
#0 [internal function]: Illuminate\Database\Query\Builder->where('updated_at', '>=', NULL)
#1 /home/forge/michaeljhopkins.com/releases/20151125180207/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(546): call_user_func_array(Array, Array)
#2 /home/forge/michaeljhopkins.com/releases/20151125180207/vendor/pragmarx/tracker/src/Vendor/Laravel/Models/Base.php(45): Illuminate\Database\Eloquent\Builder->where('updated_at', '>=', NULL)
#3 [internal function]: PragmaRX\Tracker\Vendor\Laravel\Models\Base->scopePeriod(Object(Illuminate\Database\Eloquent\Builder), Object(PragmaRX\Tracker\Support\Minutes))
#4 /home/forge/michaeljhopkins.com/releases/20151125180207/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(829): call_user_func_array(Array, Array)
#5 /home/forge/michaeljhopkins.com/releases/20151125180207/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(940): Illuminate\Database\Eloquent\Builder->callScope('scopePeriod', Array)
#6 /home/forge/michaeljhopkins.com/releases/20151125180207/vendor/pragmarx/tracker/src/Data/Repositories/Session.php(213): Illuminate\Database\Eloquent\Builder->__call('period', Array)
#7 /home/forge/michaeljhopkins.com/releases/20151125180207/vendor/pragmarx/tracker/src/Data/RepositoryManager.php(365): PragmaRX\Tracker\Data\Repositories\Session->last(Object(PragmaRX\Tracker\Support\Minutes), true)
#8 /home/forge/michaeljhopkins.com/releases/20151125180207/vendor/pragmarx/tracker/src/Tracker.php(348): PragmaRX\Tracker\Data\RepositoryManager->getLastSessions(Object(PragmaRX\Tracker\Support\Minutes), true)
#9 /home/forge/michaeljhopkins.com/releases/20151125180207/bootstrap/cache/compiled.php(6017): PragmaRX\Tracker\Tracker->sessions(Object(PragmaRX\Tracker\Support\Minutes))
#10 /home/forge/michaeljhopkins.com/releases/20151125180207/vendor/pragmarx/tracker/src/Vendor/Laravel/Controllers/Stats.php(85): Illuminate\Support\Facades\Facade::__callStatic('sessions', Array)
#11 /home/forge/michaeljhopkins.com/releases/20151125180207/vendor/pragmarx/tracker/src/Vendor/Laravel/Controllers/Stats.php(61): PragmaRX\Tracker\Vendor\Laravel\Controllers\Stats->visits()
#12 /home/forge/michaeljhopkins.com/releases/20151125180207/vendor/pragmarx/tracker/src/Vendor/Laravel/Controllers/Stats.php(52): PragmaRX\Tracker\Vendor\Laravel\Controllers\Stats->showPage('visits')
#13 [internal function]: PragmaRX\Tracker\Vendor\Laravel\Controllers\Stats->index()
#14 /home/forge/michaeljhopkins.com/releases/20151125180207/bootstrap/cache/compiled.php(8853): call_user_func_array(Array, Array)
#15 /home/forge/michaeljhopkins.com/releases/20151125180207/bootstrap/cache/compiled.php(8922): Illuminate\Routing\Controller->callAction('index', Array)
#16 /home/forge/michaeljhopkins.com/releases/20151125180207/bootstrap/cache/compiled.php(8902): Illuminate\Routing\ControllerDispatcher->call(Object(PragmaRX\Tracker\Vendor\Laravel\Controllers\Stats), Object(Illuminate\Routing\Route), 'index')
#17 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 /home/forge/michaeljhopkins.com/releases/20151125180207/bootstrap/cache/compiled.php(9564): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#19 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /home/forge/michaeljhopkins.com/releases/20151125180207/bootstrap/cache/compiled.php(9546): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#21 /home/forge/michaeljhopkins.com/releases/20151125180207/bootstrap/cache/compiled.php(8903): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#22 /home/forge/michaeljhopkins.com/releases/20151125180207/bootstrap/cache/compiled.php(8888): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(PragmaRX\Tracker\Vendor\Laravel\Controllers\Stats), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'index')
#23 /home/forge/michaeljhopkins.com/releases/20151125180207/bootstrap/cache/compiled.php(7842): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'PragmaRX\\Tracke...', 'index')
#24 /home/forge/michaeljhopkins.com/releases/20151125180207/bootstrap/cache/compiled.php(7813): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#25 /home/forge/michaeljhopkins.com/releases/20151125180207/bootstrap/cache/compiled.php(7466): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#26 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 /home/forge/michaeljhopkins.com/releases/20151125180207/bootstrap/cache/compiled.php(9564): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#28 /home/forge/michaeljhopkins.com/releases/20151125180207/app/Http/Middleware/SentinelAdmin.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 [internal function]: Me\Http\Middleware\SentinelAdmin->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /home/forge/michaeljhopkins.com/releases/20151125180207/bootstrap/cache/compiled.php(9556): call_user_func_array(Array, Array)
#31 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
```

**Comment by freel132** [comment]
I have same issue

**Comment by Mohamed-Zedan** [comment]
I have same issue too.
@antonioribeiro

**Comment by pilishen** [comment]
i think it's a problem when you hit "Today" in the up right corner. sorry i don't know how to fix it

**Comment by tyszku** [comment]
I had the same problem. I hit "Today" filter and got similar error. I handle it by visiting: [URL]/stats?days=1

Hope this help.

**Comment by antonioribeiro** [comment]
Looks like fixed by the last commits.
